### ISSUE TITLE
some zone compute error

### ISSUE THREAD

**Issue by Moliam97** [tjko/TinyTZ#2]
Africa/Casablanca is <+01>-1.
There is summer time in this area, but the calculated offsets of rule[0] and rule[1] are both 3600, which will lead to calculation errors when it comes to winter time. How should this be handled?

**Comment by tjko** [comment]
`<+01>-1` doesn't seem like valid POSIX timezone string (?)

This library expects POSIZ TZ string (IEEE) as described here: https://www.gnu.org/software/libc/manual/html_node/TZ-Variable.html


On Linux one can usually "convert" timezone specified as _region/city_ by looking files under /usr/share/zoneinfo:

```
$ tail -1 /usr/share/zoneinfo/America/Los_Angeles 
PST8PDT,M3.2.0,M11.1.0
$ tail -1 /usr/share/zoneinfo/Europe/Paris 
CET-1CEST,M3.5.0,M10.5.0/3
```

But looks like results for Casablanca don't seem to conform results for other time zones....
```
$ tail -1 /usr/share/zoneinfo/Africa/Casablanca 
<+01>-1
```

Does something like this work?
`UTC0DST`

It would seem to result same local time on a Linux box at least:
```
$ TZ=Africa/Casablanca date
Thu 27 Jul 2023 08:35:21 PM +01
$ TZ=UTC0DST date
Thu 27 Jul 2023 08:35:22 PM DST
```

**Comment by Moliam97** [comment]
`TZ=Africa/Casablanca  date -s "2023-12-01 02:00:00 UTC"`
`TZ=Africa/Casablanca  date -s "2023-03-28 02:00:00 UTC"`
The time zone printed out by the user in two ways is inconsistent.
Do you know how this should be parsed?

**Comment by tjko** [comment]
Probably not possible to convert Africa/Casablanca timezone to a POSIX TZ sting, since daylight savings time seems to be changing yearly:  https://github.com/tzinfo/tzinfo/issues/98

**Comment by Moliam97** [comment]
Today, I used the linux side to test whether the string that does not contain the daylight saving time format may contain daylight saving time. There are two
1. Africa/Casablanc
2. Africa/El_Aaiun
